;;; site-lisp-loaddefs.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from ../site-lisp/consult-citre.el

(autoload 'consult-citre "../site-lisp/consult-citre" "\
Read a tag from minibuffer and jump to the tag.

(fn INITIAL)" t)
(register-definition-prefixes "../site-lisp/consult-citre" '("consult-citre-"))


;;; Generated autoloads from ../site-lisp/edit-inline-string.el

(autoload 'edit-inline-string "../site-lisp/edit-inline-string" "\
Edit the embedded code within a separate buffer." t)
(register-definition-prefixes "../site-lisp/edit-inline-string" '("edit-inline-string-"))


;;; Generated autoloads from ../site-lisp/evil-ts.el

(register-definition-prefixes "../site-lisp/evil-ts" '("evil-ts-"))


;;; Generated autoloads from ../site-lisp/mg-pyvenv.el

(autoload 'mg-pyvenv-conda-activate "../site-lisp/mg-pyvenv" "\
Activate a conda environment.

(fn &optional PATH)" t)
(autoload 'mg-pyvenv-conda-deactivate "../site-lisp/mg-pyvenv" "\
Deactivate all the conda environments, including the base environment." t)
(autoload 'mg-pyvenv-venv-activate "../site-lisp/mg-pyvenv" "\
Activate a python virtual environment.

(fn &optional PATH)" t)
(autoload 'mg-pyvenv-venv-deactivate "../site-lisp/mg-pyvenv" "\
Deactivate the current python virtual environment." t)
(autoload 'mg-pyvenv-poetry-activate "../site-lisp/mg-pyvenv" "\
Activate a poetry virtual environment.
If only one environment exists, activate it directly. Otherwise, prompt for selection.

(fn PATH)" t)
(autoload 'mg-pyvenv-poetry-deactivate "../site-lisp/mg-pyvenv" "\
Deactivate the current poetry virtual environment." t)
(register-definition-prefixes "../site-lisp/mg-pyvenv" '("mg-pyvenv-"))


;;; Generated autoloads from ../site-lisp/termint-aider.el

 (autoload #'termint-aider-start "termint-aider" nil t)
(register-definition-prefixes "../site-lisp/termint-aider" '("termint-aider-"))

;;; End of scraped data

(provide 'site-lisp-loaddefs)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; site-lisp-loaddefs.el ends here
