;;; site-lisp-loaddefs.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from ../site-lisp/consult-citre.el

(autoload 'consult-citre "../site-lisp/consult-citre" "\
Read a tag from minibuffer and jump to the tag.

(fn INITIAL)" t)
(register-definition-prefixes "../site-lisp/consult-citre" '("consult-citre-"))


;;; Generated autoloads from ../site-lisp/dashverse.el

(autoload 'dashverse-mode "../site-lisp/dashverse" "\
Minor mode used on the dashverse welcome screen.

Its keymap is installed via `emulation-mode-map-alists' so that it
takes precedence over Evil and other minor modes.

This is a minor mode.  If called interactively, toggle the `Dashverse
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `dashverse-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

\\{dashverse-mode-map}

(fn &optional ARG)" t)
(autoload 'dashverse-emacs-startup-time "../site-lisp/dashverse" "\
Measure the startup time until the welcome screen is displayed.
More accurate than `emacs-init-time'." t)
(autoload 'dashverse-refresh-verses "../site-lisp/dashverse" "\
Refresh verses in the scratch buffer." t)
(register-definition-prefixes "../site-lisp/dashverse" '("dashverse-"))


;;; Generated autoloads from ../site-lisp/edit-inline-string.el

(autoload 'edit-inline-string "../site-lisp/edit-inline-string" "\
Edit the embedded code within a separate buffer." t)
(register-definition-prefixes "../site-lisp/edit-inline-string" '("edit-inline-string-"))


;;; Generated autoloads from ../site-lisp/evil-ts.el

(register-definition-prefixes "../site-lisp/evil-ts" '("evil-ts-"))


;;; Generated autoloads from ../site-lisp/pyc-env.el

(autoload 'pyc-env-conda-activate "../site-lisp/pyc-env" "\
Activate a conda environment.

(fn &optional PATH)" t)
(autoload 'pyc-env-conda-deactivate "../site-lisp/pyc-env" "\
Deactivate all the conda environments, including the base environment." t)
(autoload 'pyc-env-venv-activate "../site-lisp/pyc-env" "\
Activate a python virtual environment.

(fn &optional PATH)" t)
(autoload 'pyc-env-venv-deactivate "../site-lisp/pyc-env" "\
Deactivate the current python virtual environment." t)
(autoload 'pyc-env-poetry-activate "../site-lisp/pyc-env" "\
Activate a poetry virtual environment.
If only one environment exists, activate it directly. Otherwise, prompt for selection.

(fn PATH)" t)
(autoload 'pyc-env-poetry-deactivate "../site-lisp/pyc-env" "\
Deactivate the current poetry virtual environment." t)
(register-definition-prefixes "../site-lisp/pyc-env" '("pyc-env-"))


;;; Generated autoloads from ../site-lisp/termint-aider.el

 (autoload #'termint-aider-start "termint-aider" nil t)
(register-definition-prefixes "../site-lisp/termint-aider" '("termint-aider-"))

;;; End of scraped data

(provide 'site-lisp-loaddefs)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; site-lisp-loaddefs.el ends here
