;;; init.el -*- lexical-binding: t; -*-

;; increase gc threshold to speedup starting up
(setq gc-cons-percentage 0.6)
(setq gc-cons-threshold most-positive-fixnum)

(push (file-name-concat user-emacs-directory "config") load-path)
(setq custom-file (file-name-concat user-emacs-directory "custom.el"))

;; Generate the native autoload cache on the first startup.
(unless (file-exists-p
         (expand-file-name ".user-lisp-autoloads.el" user-lisp-directory))
    (prepare-user-lisp))

;; Emacs normally loads the autoload cache in `user-lisp-directory' before it
;; runs this file, but it skips that step in batch mode, where `--batch' implies
;; `-q' and Emacs reads that as the user wanting none of their own Lisp.
;; Without the call below, `emacs --batch -l init.el' fails on the first
;; function that lives in `user-lisp'.  We only load the cache here; rebuilding
;; it would recompile that whole directory, which no batch job should be doing.
(unless init-file-user
    (prepare-user-lisp t))

(setq use-package-expand-minimally t
      ;; use-package is a macro. Don't let the macro expands into
      ;; codes with too much of irrelevant checks.
      ;; Straight is my package manager, don't let package.el get
      ;; involved.
      use-package-always-defer t
      ;; This is a useful trick to speed up your startup time. Only
      ;; use `require' when it's necessary. By setting the
      ;; `use-package-always-defer' option to t, use-package won't
      ;; call `require' in all cases unless you explicitly include
      ;; :demand t'. This will prevent unnecessary package loading and
      ;; speed up your Emacs startup time.
      straight-check-for-modifications '(find-when-checking)
      ;; This is a useful trick to further optimize your startup
      ;; time. Instead of using `straight-check-for-modifications' to
      ;; check if a package has been modified, you can manually
      ;; rebuild the package by `straight-rebuild-package' when you
      ;; know its source code has changed. This avoids the overhead of
      ;; the check. Make sure you know what you are doing here when
      ;; setting this option.
      debug-on-error t
      load-prefer-newer t)

;; bootstrap straight.el, copied from
;; URL: `https://github.com/radian-software/straight.el#getting-started'
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
    (unless (file-exists-p bootstrap-file)
        (with-current-buffer
                (url-retrieve-synchronously
                 "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
                 'silent 'inhibit-cookies)
            (goto-char (point-max))
            (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))

;; Useful for analyzing startup performance.  Helps identify which
;; packages significantly delay initialization.
;; (straight-use-package 'benchmark-init)
;; (benchmark-init/activate)
;; (benchmark-init/show-durations-tabulated)

(require 'config-utils)
(require 'config-basics)
(require 'config-ui)
(require 'config-colorscheme)
(require 'config-evil)
(require 'config-completion-company)
(require 'config-minibuffer)
(require 'config-vcs)
(require 'config-elisp)
(require 'config-org)
(require 'config-langs)
(require 'config-langtools)
(require 'config-os)
(require 'config-apps)
(require 'config-email)
(require 'config-misc)

;; I personally HATE custom.el. But I don't think I have a better
;; place to store temporary data like API keys.
(when (file-exists-p custom-file)
    (load custom-file nil t))

;; Load nix-generated.el to import Nix-injected settings.
;; This file is generated by home-manager.
;; load only when file exists
(let ((nix-generated-file (expand-file-name "emacs/nix-generated.el"
                                            (or (getenv "XDG_STATE_HOME") "~/.local/state"))))
    (when (file-exists-p nix-generated-file)
        (load nix-generated-file nil t)))

(setq debug-on-error nil)

;; after started up, reset GC threshold to normal.
(run-with-idle-timer 4 nil
                     (lambda ()
                         "Clean up gc."
                         (setq gc-cons-threshold  67108864) ; 64M
                         (setq gc-cons-percentage 0.1) ; original value
                         (garbage-collect)))

(provide 'init)
;;; init.el ends here
