;;; my-site-lisp-loaddefs.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from consult-citre.el

(autoload 'consult-citre "consult-citre" "\
Read a tag from minibuffer and jump to the tag.

(fn INITIAL)" t)
(register-definition-prefixes "consult-citre" '("consult-citre-"))


;;; Generated autoloads from evil-ts.el

(register-definition-prefixes "evil-ts" '("evil-ts-"))


;;; Generated autoloads from minuet.el

(autoload 'minuet-completion-in-region "minuet" "\
Complete code in region with LLM." t)
(register-definition-prefixes "minuet" '("minuet-"))

;;; End of scraped data

(provide 'my-site-lisp-loaddefs)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; my-site-lisp-loaddefs.el ends here
